import type { Server } from '~/components/frontpage/Server.vue'

export function useServers() {
  const servers: Server[] = [
    {
      position: 1,
      icon: 'https://api.mcsrvstat.us/icon/hypixel.net',
      banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200',
      name: 'Hypixel',
      description: 'The largest Minecraft server in the world with tons of unique minigames!',
      ip: 'mc.hypixel.net',
      tags: ['Minigames', 'Skyblock', 'Bedwars'],
      onlinePlayers: 45232,
      maxPlayers: 200000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 2,
      icon: 'https://api.mcsrvstat.us/icon/cubecraft.net',
      banner: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=1200',
      name: 'CubeCraft Games',
      description: 'Home of EggWars, SkyWars, and many more exciting games!',
      ip: 'play.cubecraft.net',
      tags: ['Minigames', 'EggWars', 'SkyWars'],
      onlinePlayers: 8921,
      maxPlayers: 50000,
      version: '1.9 - 1.20.4',
    },
    {
      position: 3,
      icon: 'https://api.mcsrvstat.us/icon/mineplex.com',
      banner: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200',
      name: 'Mineplex',
      description: 'A massive Minecraft server with a variety of fun games and modes.',
      ip: 'us.mineplex.com',
      tags: ['Minigames', 'Survival', 'Creative'],
      onlinePlayers: 3456,
      maxPlayers: 30000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 4,
      icon: 'https://api.mcsrvstat.us/icon/mc.prison.org',
      name: 'PrisonMC',
      description: 'The ultimate prison experience with custom enchants and mines.',
      ip: 'play.prisonmc.org',
      tags: ['Prison', 'Economy', 'PvP'],
      onlinePlayers: 1234,
      maxPlayers: 5000,
      version: '1.16 - 1.20.4',
    },
    {
      position: 5,
      icon: 'https://api.mcsrvstat.us/icon/manacube.com',
      banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200',
      name: 'ManaCube',
      description: 'Featuring Skyblock, Parkour, Survival, and much more!',
      ip: 'play.manacube.com',
      tags: ['Skyblock', 'Parkour', 'Survival'],
      onlinePlayers: 2891,
      maxPlayers: 15000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 6,
      icon: 'https://api.mcsrvstat.us/icon/mc.complex-gaming.com',
      name: 'Complex Gaming',
      description: 'Pixelmon, modded survival, and vanilla experiences await.',
      ip: 'mc.complex-gaming.com',
      tags: ['Pixelmon', 'Modded', 'Survival'],
      onlinePlayers: 567,
      maxPlayers: 3000,
      version: '1.12.2',
    },
    {
      position: 7,
      icon: 'https://api.mcsrvstat.us/icon/purpleprison.org',
      banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200',
      name: 'Purple Prison',
      description: 'Top-rated prison server with amazing custom features.',
      ip: 'purpleprison.org',
      tags: ['Prison', 'Economy', 'Gangs'],
      onlinePlayers: 1823,
      maxPlayers: 10000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 8,
      icon: 'https://api.mcsrvstat.us/icon/earthmc.net',
      name: 'EarthMC',
      description: 'Build your own nation on a 1:500 scale map of Earth!',
      ip: 'play.earthmc.net',
      tags: ['Towny', 'Earth', 'Nations'],
      onlinePlayers: 892,
      maxPlayers: 5000,
      version: '1.17 - 1.20.4',
    },
    {
      position: 9,
      icon: 'https://api.mcsrvstat.us/icon/play.minesuperior.com',
      banner: 'https://images.unsplash.com/photo-1552820728-8b83bb6b2b0c?w=1200',
      name: 'MineSuperior',
      description: 'Factions, Prison, Skyblock and more competitive gamemodes.',
      ip: 'play.minesuperior.com',
      tags: ['Factions', 'Prison', 'Skyblock'],
      onlinePlayers: 445,
      maxPlayers: 8000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 10,
      icon: 'https://api.mcsrvstat.us/icon/play.extremecraft.net',
      name: 'ExtremeCraft',
      description: 'Cracked server with Survival, Skyblock, and Creative modes.',
      ip: 'play.extremecraft.net',
      tags: ['Cracked', 'Survival', 'Skyblock'],
      onlinePlayers: 2134,
      maxPlayers: 20000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 11,
      icon: 'https://api.mcsrvstat.us/icon/mccentral.org',
      banner: 'https://images.unsplash.com/photo-1493711662062-fa541f7f3d24?w=1200',
      name: 'MCCentral',
      description: 'Prison, KitPvP, Skyblock, and tons of minigames!',
      ip: 'mccentral.org',
      tags: ['Prison', 'KitPvP', 'Skyblock'],
      onlinePlayers: 1567,
      maxPlayers: 12000,
      version: '1.8 - 1.20.4',
    },
    {
      position: 12,
      icon: 'https://api.mcsrvstat.us/icon/jartex.fun',
      name: 'JartexNetwork',
      description: 'Bedwars, Skywars, and practice PvP server.',
      ip: 'jartex.fun',
      tags: ['Bedwars', 'Skywars', 'Practice'],
      onlinePlayers: 3210,
      maxPlayers: 25000,
      version: '1.8 - 1.20.4',
    },
  ]

  return { servers }
}
